name: servicebook_cn
description: "Приложение для учёта обслуживания китайских автомобилей. ServiceBook помогает вести историю ТО, расходов и документов."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  
  # Новые пакеты
  flutter_local_notifications: ^18.0.0
  timezone: ^0.9.0
  pdf: ^3.11.0
  printing: ^5.13.0
  share_plus: ^10.0.0
  file_picker: ^8.0.0
  image_picker: ^1.1.0
  path_provider: ^2.1.0
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png